print("India's History Timeline :- ")
print("1. 2500–1600 BC = Harappan (Indus Valley) Civilisation. ")
print("2. 1500 BC onwards = Central Asian Aryans migrate to the Indian subcontinent. ")
print("3. 563 BC = Birth of Siddhartha Gautama, the Buddha. ")
print("4. 325 BC = Chandragupta Maurya founds the Mauryan empire. ")
print("5. 260 BC = King Ashoka converts to Buddhism. ")
print("6. AD 320 = Gupta empire is established.")
print("7. 1200 = Muslim armies conquer northern India; decline of Buddhism.")
print("8. The Delhi Sultanate = 1206")
print("9. 1451 = Buhlbal Lodi, an Afghan noble, captures the throne and founds the Lodhi dynasty. ")
print("10. 14th–16th century = Islam is established throughout the North. ")