Dish = input("Please enter your first favourite dish : ")
Dish1 = input("Please enter your second favourite dish : ")
Dish2 = input("Please enter your third favourite dish : ")
print()
print("My First Favourite Dish is " + Dish + ("."))
print()
print("My Second Favourite Dish is " + Dish1 + ("."))
print()
print("My Third Favourite Dish is " + Dish2 + ("."))
