Name = input("Please enter your name : ")
School = input("Please enter your School's name : ")
Address = input("Please enter your Address : ")
print()
print("My Name is " + Name + ("."))
print()
print("My School's Name is " + School + ("."))
print()
print("My Address is " + Address + ("."))
