Ques1 = input("What is Capital of India? ")
Ques2 = input("What is Capital of Madhya Pradesh? ")
Ques3 = input("What is Capital Of Maharashtra? ")
print()
print("Capital of India is " + Ques1)
print()
print("Capital of Madhya Pradesh is " + Ques2)
print()
print("Capital of Maharashtra is " + Ques3)